typography_spectrum: 0.014756629709154367
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15657324064522982
  lightness: 0.9690034550148994
  saturation: 0.007415941683575511
  rhythmicContrast: 0.9729568944312632
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4340988593176007
analytics:
  google: null
  facebook: null
  twitter: null
name: paulsmith
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Paul Smith
description: music + life
purpose: []
